[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
(
  ^/lib/vendor/
)
'''

[tool.isort]
profile = "black"
line_length = 100
skip_glob = ["*/vendor/*"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "Q"]
ignore = ["E203", "E231", "E501"]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "vendor",
]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = ["machine.*", "network.*", "picographics.*", "pimoroni.*"]
ignore_missing_imports = true