"""Type stubs for MicroPython network module"""
from typing import List, Optional, Tuple, Union

# Constants
STA_IF: int
AP_IF: int

# Classes
class WLAN:
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def connect(self, ssid: str, password: str, bssid: Optional[bytes] = None, timeout: Optional[int] = None) -> None: ...
    def disconnect(self) -> None: ...
    def scan(self) -> List[Tuple[bytes, bytes, int, int, int, int]]: ...
    def status(self) -> int: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Optional[Tuple[str, str, str, str]] = None) -> Tuple[str, str, str, str]: ...